name = "expense-tracker"
main = "functions/_middleware.js"
compatibility_date = "2023-10-30"

[env.production.vars]
# 在Cloudflare Pages设置环境变量
# ADMIN_PASSWORD = "your-secure-password-here"

[[env.production.d1_databases]]
binding = "DB"
database_name = "db1"
database_id = "cd369d0c-31e7-41ad-bc42-b3921be01efe"

[env.development.vars]
ADMIN_PASSWORD = "dev-password"

[[env.development.d1_databases]]
binding = "DB"
database_name = "db1"
preview_database_id = "cd369d0c-31e7-41ad-bc42-b3921be01efe"
